server:
  port: 6868
eureka:
  client:
    fetch-registry: false #是否从eureka服务端获取注册信息
    register-with-eureka: false #是否将本模块注册到eureka服务端
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka  #Eureka客户端与Eureka服务端进行交互的地址
  server:
    enable-self-preservation: false